#    '||    ||'     |      ..|'''.|  '||'   ..|'''.| '||''|.   ..|''||   '|| '||'  '|' '||''''|  '||''|.   '||''''|  '||''|.
#     |||  |||     |||    .|'     '   ||  .|'     '   ||   || .|'    ||   '|. '|.  .'   ||  .     ||   ||   ||  .     ||   ||
#     |'|..'||    |  ||   ||    ....  ||  ||          ||...|' ||      ||   ||  ||  |    ||''|     ||''|'    ||''|     ||    ||
#     | '|' ||   .''''|.  '|.    ||   ||  '|.      .  ||      '|.     ||    ||| |||     ||        ||   |.   ||        ||    ||
#    .|. | .||. .|.  .||.  ''|...'|  .||.  ''|....'  .||.      ''|...|'      |   |     .||.....| .||.  '|' .||.....| .||...|'

# RainbowEdit 彩虹编辑。
# 感谢使用 妙控动力 MagicPowered 插件。
# 心中所想事皆成，一路前行俱坦途。
# 春风秋月冬雪丰，留着残荷听雨声。冷眼看浮生如梦烟雨化飞龙。

Message:
  prefix: "§7[§b彩虹编辑§7]"
  no-item-in-hand: "&7错误, 您的主手中没有物品"
  item-has-no-lore: "&7错误, 您主手中的物品没有描述"
  name-set-successfully: "&7成功设置新的名称: %new_name%"
  invalid-lore-line: "&7错误, 指定的描述行 &b%line_invalid% &7不存在"
  lore-add-successfully: "&7成功添加新的描述行: %add_str%"
  old-string-not-found: "&7错误, 第 &b%replace_line% &7行中没有指定的子串: %replace_old%"
  lore-replaced-successfully: "&7成功将 &b%replace_line% &7行的 %replace_old% 替换为 %replace_new%"
  lore-line-set: "&7第 &b%set_line% &7行已更新为: %set_new%"
  lore-line-inserted: "&7在 &b%insert_line% &7行 &b%insert_mode% &7成功插入: %insert_str%"
  lore-line-removed: "&7第 &b%remove_line% &7行描述已被删除"
  lore-cleared-successfully: "&7您主手中物品的所有描述行已被删除"
  entered-preview-mode: "&7进入预览模式, 物品所在的快捷栏已锁定"
  not-in-preview-mode: "&7错误, 您并不处于预览模式中"
  now-in-preview-mode: "&7错误, 您已经处于预览模式中"
  applied-preview-changes: "&7退出预览模式, 并且应用预览模式中的修改"
  canceled-preview-changes: "&7退出预览模式, 并且撤销预览模式中的更改"
  cannot-move-preview-item: "&7错误, 您无法移动处于预览模式锁定快捷栏中的物品"
  cannot-drop-preview-item: "&7错误, 您无法丢弃处于预览模式锁定快捷栏中的物品"

ActionBar:
  1: "&b彩虹编辑 &7[&c&l↓&7---------------------------] &b预览模式"
  2: "&b彩虹编辑 &7[----&c&l↓&7-----------------------] &b预览模式"
  3: "&b彩虹编辑 &7[-------&c&l↓&7--------------------] &b预览模式"
  4: "&b彩虹编辑 &7[----------&c&l↓&7-----------------] &b预览模式"
  5: "&b彩虹编辑 &7[--------------&c&l↓&7-------------] &b预览模式"
  6: "&b彩虹编辑 &7[-----------------&c&l↓&7----------] &b预览模式"
  7: "&b彩虹编辑 &7[--------------------&c&l↓&7-------] &b预览模式"
  8: "&b彩虹编辑 &7[------------------------&c&l↓&7---] &b预览模式"
  9: "&b彩虹编辑 &7[---------------------------&c&l↓&7] &b预览模式"